services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app:/app
    expose:
      - "8000"
    networks:
      - fastapi_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:8080" # puerto 80 en producción
      - "443:443" # Si configuras SSL
    depends_on:
      - api
    networks:
      - fastapi_network

  # Base de datos PostgreSQL (opcional)
  #
  # db:
  #   image: postgres:15
  #   container_name: laravel-postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: fastapi
  #     POSTGRES_USER: fastapi
  #     POSTGRES_PASSWORD: secret
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   networks:
  #     - fastapi_network

#volumes:
  #postgres_data:

networks:
  fastapi_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.12.0/28
          gateway: 172.42.12.1