"""Tablas Negocio

Revision ID: 167ef704f2cc
Revises: 56b104d37b94
Create Date: 2025-07-18 21:27:30.443728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '167ef704f2cc'
down_revision: Union[str, Sequence[str], None] = '56b104d37b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negocio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mapa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('negocio')
    # ### end Alembic commands ###
