"""Tabla Plato

Revision ID: 37e2cf224f3e
Revises: 8784df9cbdda
Create Date: 2025-06-16 19:58:18.148225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '37e2cf224f3e'
down_revision: Union[str, None] = '8784df9cbdda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingredientes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('foto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=True),
    sa.Column('platoscategoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocio.id'], ),
    sa.ForeignKeyConstraint(['platoscategoria_id'], ['platoscategoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platos')
    # ### end Alembic commands ###
