"""Tablas Platos

Revision ID: 88d93fc91cda
Revises: 377ac35271ec
Create Date: 2025-07-19 19:49:18.306308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88d93fc91cda'
down_revision: Union[str, Sequence[str], None] = '377ac35271ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=True),
    sa.Column('platoscategoria_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingredientes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('foto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocio.id'], ),
    sa.ForeignKeyConstraint(['platoscategoria_id'], ['platoscategoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platos')
    # ### end Alembic commands ###
