"""Agregar campo perfil_id a Usuario

Revision ID: a1e9f34a8877
Revises: a421b6e6c664
Create Date: 2025-06-20 16:15:15.779759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e9f34a8877'
down_revision: Union[str, None] = 'a421b6e6c664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('perfil_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuario', 'perfil', ['perfil_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'perfil_id')
    # ### end Alembic commands ###
